### PR TITLE
heavy unet tests - not working yet

### PR DESCRIPTION
**Pull request by mzouink**
By running dacapo i hit multiple bugs sor i created a heavier test which test most unet scenario
I think we need to make sure that all the unittest works + we need to have more realistic tests
@pattonw

### CODE REVIEW

**Comment by mzouink** [comment]
related: https://github.com/janelia-cellmap/dacapo/issues/331

**Comment by pattonw** [comment]
Looks like we both fixed the dims error in different places. 
The function signature of `input_shape` already defined the return type as coordinate, so it is a bug if input_shape isn't already a coordinate. I fixed it inside the cnnectome unet

**Comment by pattonw** [comment]
Just want to make a note here for the tests that are still failing they are of the following form:

1. "The size of tensor a (188) must match the size of tensor b (94) at non-singleton dimension ...". This is caused by the upsampling input data and comparing to gt that is at the same resolution as the input data. We should create a separate dataset fixture for upsampled data.
2. Assertion Errors. These are caused by us checking for some threshold absolute difference between the weights before and after training a few iterations. Not sure if this assumption always holds.

**Comment by mzouink** [comment]
> Looks like we both fixed the dims error in different places. The function signature of `input_shape` already defined the return type as coordinate, so it is a bug if input_shape isn't already a coordinate. I fixed it inside the cnnectome unet

i removed my change

**Comment by pattonw** [comment]
> i agree with you but we need to figure a way to test if the model is training. because i remember we had a problem with distance without adding 4 dimension
I think this was only after validation, we saw a strange jump in the loss. It was caused by putting the model in eval mode for validation, and then not switching it back after completing prediction. I think this went unnoticed because it only makes a difference for things like batchnorm, dropout, and other layers that have different behavior between train and eval. `Batchnorm` looks like it was added by default so when we were expecting the model to behave the same in train and eval we were getting this strange behavior.

I'm pretty sure thats fixed now and I haven't seen this jump in the minimal tutorial anymore.

We should be testing that our models train, but I think a better way to do this is on full examples, so we should have the minimal tutorial cover more cases (instance/semantic, 2D/3D, multi class/single class, single channel raw/multi channel raw) and test that the loss and validation metrics reach reasonable values

**Comment by pattonw** [comment]
I'm thinking something like this:
[benchmark action repo](https://github.com/benchmark-action/github-action-benchmark)
[example results](https://benchmark-action.github.io/github-action-benchmark/dev/bench/)

Except instead of tracking time (which we could do), we would also track loss / validation scores for each of our tutorials

This repo looks pretty tailor made to performance benchmarking, but we may be able to hack in the data we want to track, or find a similar/better way

**Comment by mzouink** [comment]
I added upsample unet
+ i added validate_run for unet test which is failing 
 E       RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by mzouink** [comment]
> I'm thinking something like this: [benchmark action repo](https://github.com/benchmark-action/github-action-benchmark) [example results](https://benchmark-action.github.io/github-action-benchmark/dev/bench/)
> 
> Except instead of tracking time (which we could do), we would also track loss / validation scores for each of our tutorials
> 
> This repo looks pretty tailor made to performance benchmarking, but we may be able to hack in the data we want to track, or find a similar/better way

this will be a great way to benchmark and to show progress

**Comment by mzouink** [comment]
I added a test for the model to check if they are 2d conv or 3d conv and i found that this code (i took from the tutorial) is returing a 3D unet.
```python
@pytest.fixture()
def unet_architecture():
    yield CNNectomeUNetConfig(
        name="tmp_unet_architecture",
        input_shape=(2, 132, 132),
        eval_shape_increase=(8, 32, 32),
        fmaps_in=1,
        num_fmaps=8,
        fmaps_out=8,
        fmap_inc_factor=2,
        downsample_factors=[(1, 4, 4), (1, 4, 4)],
        kernel_size_down=[[(1, 3, 3)] * 2] * 3,
        kernel_size_up=[[(1, 3, 3)] * 2] * 2,
        constant_upsample=True,
        padding="valid",
    )

```

 can you show me how to train a 2d unet with slices of 3d data

**Comment by mzouink** [comment]
All the error we still have now are for 2d unet.

I changed the assert in the test_train to just check if there is a difference in the weights

**Comment by mzouink** [comment]
@pattonw  is this the right way to create 2d unet :

```python
arch_conf =  CNNectomeUNetConfig(
        name="unet2d_architecture",
        input_shape=(132, 132),
        eval_shape_increase=(32, 32),
        fmaps_in=1,
        num_fmaps=8,
        fmaps_out=8,
        fmap_inc_factor=2,
        downsample_factors=[(4, 4), (4, 4)],
        kernel_size_down=[[(3, 3)] * 2] * 3,
        kernel_size_up=[[(3, 3)] * 2] * 2,
        constant_upsample=True,
        padding="valid",
    )
```

**Comment by pattonw** [comment]
Hmm, you defined two different valid UNets that are both essentially 2D.

If you have 3D data, and you want to process it in 2D slices, the 3D unet with all up/down sampling set to 1 and all kernel sizes set to 1 to make a 3D model that operates on 2D slices is the appropriate model to build. If your data is 2D then you need to define your model with only two dimensions.

**Comment by mzouink** [comment]
this is the old way i used to define 2d unet for 3d data: 

```python
architecture_config = CNNectomeUNetConfig(
    name="example_unet",
    input_shape=(1, 132, 132),
    eval_shape_increase=(8, 32, 32),
    fmaps_in=2,
    num_fmaps=8,
    fmaps_out=8,
    fmap_inc_factor=2,
    downsample_factors=[(1, 4, 4), (1, 4, 4)],
    kernel_size_down=[[(1, 3, 3)] * 2] * 3,
    kernel_size_up=[[(1, 3, 3)] * 2] * 2,
    constant_upsample=True,
    padding="valid",
)
```
but for this one the model is using conv3d not conv2d

**Comment by pattonw** [comment]
Yes, if you have 3D data, you should be using 3D convolutions, even if you want a 2D model, you just use (1, 3, 3) as the kernel shape. Its still a `Conv3D` class though.
This is convenient because you can then pass a 3D cube through your model at predict time. e.g. a `(channelsx200x200x200)` can be processed by a model defined with kernel size `(1, 3, 3)`, allowing you to generate predictions with a 2D model in 3D chunks so you can save it to zarr with a reasonable chunk size.
If you made your model use 2D convolutions you would have to do a bunch of axis permutations to turn one of the physical dimensions into a batch dimension and back.

**Comment by pattonw** [comment]
I made a pull request onto this branch that has 2D and 3D data with appropriate models, as well as a psuedo 2D model on 3D data

**Comment by pattonw** [comment]
Yeah I think so

**Pull request merged**
