### PR TITLE
57 parallel blockwise processing

### PR DESCRIPTION
**Pull request by rhoadesScholar**

### CODE REVIEW

**Comment by rhoadesScholar** [comment]
@neptunes5thmoon @adjavon This is the reference that I've been working from (cuz I know it works): https://github.com/janelia-cellmap/utils-share/blob/d8f368e45965a991330f46c19871f37d1ef59cee/rhoadesj/daisy/segment_blockwise.py#L157

**Comment by neptunes5thmoon** [comment]
changing the iteration to a string fixes something (`dacpo/blockwise/predict_worker.py:198`), but then each worker fails because the options fixture isn't passed to the spawned processes. Daisy hangs, so not pushing.

**Comment by rhoadesScholar** [comment]
> changing the iteration to a string fixes something (`dacapo/blockwise/predict_worker.py:198`), but then each worker fails because the options fixture isn't passed to the spawned processes. Daisy hangs, so not pushing.

is this then an issue with pytest and daisy interacting, not necessarily a real issue?

**Comment by rhoadesScholar** [comment]
Test results differ across OS

**Comment by rhoadesScholar** [comment]
Looks like this is a Daisy issue?! 
image

**Comment by rhoadesScholar** [comment]
> > changing the iteration to a string fixes something (`dacapo/blockwise/predict_worker.py:198`), but then each worker fails because the options fixture isn't passed to the spawned processes. Daisy hangs, so not pushing.
> 
> is this then an issue with pytest and daisy interacting, not necessarily a real issue?

I think I managed to make it to this error after `pip install git+https://github.com/funkelab/daisy.git@83de25690a75938a1646f2e5c44273daf3e065a8`

maybe I need to pass the path to the options file as environment variables to the workers?

**Comment by rhoadesScholar** [comment]
New error from test_validate.py (seen in the daisy worker logs):
```
Traceback (most recent call last):
  File "/nrs/cellmap/rhoadesj/dacapo/dacapo/blockwise/predict_worker.py", line 219, in <module>
    cli()
  File "/home/rhoadesj@hhmi.org/micromamba/envs/dacapo/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/rhoadesj@hhmi.org/micromamba/envs/dacapo/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/rhoadesj@hhmi.org/micromamba/envs/dacapo/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rhoadesj@hhmi.org/micromamba/envs/dacapo/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rhoadesj@hhmi.org/micromamba/envs/dacapo/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nrs/cellmap/rhoadesj/dacapo/dacapo/blockwise/predict_worker.py", line 73, in start_worker
    run_config = config_store.retrieve_run_config(run_name)
  File "/nrs/cellmap/rhoadesj/dacapo/dacapo/store/file_config_store.py", line 35, in retrieve_run_config
    run_doc = self.__load(self.runs, run_name)
  File "/nrs/cellmap/rhoadesj/dacapo/dacapo/store/file_config_store.py", line 121, in __load
    raise ValueError(f"No config with name: {name} in collection: {collection}")
ValueError: No config with name: distance_run in collection: /home/rhoadesj@hhmi.org/dacapo_runs/configs/runs
```

**Comment by rhoadesScholar** [comment]
Going to merge to `dev/main` to get others up to date (and because it fixes bugs currently in `dev/main`

**Comment by rhoadesScholar** [comment]
> Proposal: @pattonw
> 
> * [ ]  - Add compute context config to options file
> * [ ]  - Change passing of compute context to passing of path to options file
> * [ ]  - Lock options file once it starts to be used by dacapo so it can't be overwritten?

#3 can't be done in a straightforward way. The best option may be to make a copy of the options file and bury it deep within a config directory in dacapo... thoughts? @pattonw @neptunes5thmoon

**Comment by neptunes5thmoon** [comment]
maybe a copy in a temp file?

**Pull request merged**
