### PR TITLE
[WIP] use pypi versions of dependencies

### PR DESCRIPTION
**Pull request by d-v-b**
Removes git dependencies, enabling packaging of this project on pypi. This PR is currently broken until `funlib.evaluate` gets added to pypi.

### CODE REVIEW

**Comment by mzouink** [comment]
@d-v-b our problem is that the published version of `daisy` is no longer valid. 
`funlib.evaluate` and `lsd` are not published in pypi

@cmalinmayor  can you please make a new release of `daisy`
@funkey or @pattonw  can you please release `funlib.evaluate` and `lsd`

**Comment by pattonw** [comment]
`lsd` is on pypi. Unfortunately the name of `lsd` was taken so you have to use `pip install lsds`.
I published a minor update to `daisy`. I don't think there were any breaking changes in there, mostly just performance tweaks and process cleanup. but both v1.0 and v1.1 should both be valid.
`funlib.evaluate` is a bit more problematic. It depends on `graph_tool` which is a nuisance to install and is not available on pypi.

**Comment by mzouink** [comment]
@pattonw  is `graph_tool` a mandatory dependency. seams not to be used

**Comment by mzouink** [comment]
Needed: 
- [X]  LSDS
- [ ] funlib.evaluate
    - [ ] graph_tool ( check if needed )
    - [ ] relase 
- [ ] funlib.persistence
    - [ ] fix N5 order
    - [ ] merge https://github.com/funkelab/funlib.persistence/pull/4
    - [ ] publish
- [X] Daisy

**Comment by rhoadesScholar** [comment]
See https://github.com/janelia-cellmap/dacapo/pull/212
funlib.evaluate removed as a dependency by removing IoU metric not previously used for evaluation.

**Pull request closed without merging**
