### PR TITLE
feat: ✨ Add support for training on Apple M1/M2/M3 (mps) devices.

### PR DESCRIPTION
**Pull request by rhoadesScholar**
Also add log printing of device used for training.

### CODE REVIEW

**Review by rhoadesScholar — COMMENTED** [review]
Should be good 👍🏼

**Comment by rhoadesScholar** [comment]
Fixed weights being float64 in GunpowderTrainer line 317. Does train.

**Review by rhoadesScholar — COMMENTED** [review]
gtg

**Review by mzouink — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Ran locally on the minimal_tutorial (I2K). 
85+% GPU utilization, still >400% CPU. 
Ironically, it's a bit slower: 5.5 it/s vs ~8 it/s on my 2020 M1
Interestingly, the issue with poor labels after training (stripping) I had during the workshop was resolved.
🤷

**Pull request merged**
