### PR TITLE
dev/validation (starting from rhoadesj/dev validation related changes)

### PR DESCRIPTION
**Pull request by rhoadesScholar**

### CODE REVIEW

**Comment by davidackerman** [comment]
> @davidackerman I think some of these changes were stolen/adapted from your branches?
yeah looks like it!

**Review by rhoadesScholar — COMMENTED** [review]
gtg

**Review by rhoadesScholar — COMMENTED** [review]
gtg

**Review by rhoadesScholar — COMMENTED** [review]
gtg

**Pull request merged**
